refresh_rate: 100
controllers_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
serials: [585081, 585081, 585081, 585078,     585078, 585078, 585671, 585671,       585671, 585716, 585716, 585716,    585078, 585716, 585671, 585081,      586100]
channels: [0, 1, 2, 2,                        1, 0, 0, 1,                           2, 2, 1, 0,                        3, 3, 3, 3,                          0   ]
direction: [1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1]
cal_offset: { p585716: [-7.873401e-06, -8.640811e-06, -5.369075e-06, -9.134412e-06], p585081: [-1.1753291e-05, -1.665205e-06, -5.789101e-06, -1.3516285e-05], p585671: [-1.0947697e-05, -3.320165e-06, -3.3660792e-05, -1.0131858e-05], p585078: [-1.931563e-06, -3.354624e-06, -2.991408e-06, 4.554167e-06], p586100: [-4.806556e-06, 0.0, 0.0, 0.0]}
cal_factor: { p585716: [-8047.458618925634, -7797.13444299666, -7937.016560686648, -7928.506839783308], p585081: [-8078.081494936741, -7955.929737499302, -7955.528898947196, -7934.5414674585645], p585671: [-8296.606413856856, -7811.497040396405, -7859.1931117957365, -8054.896166540559], p585078: [-7838.664445341756, -8076.355897434952, -8071.7174158760245, -8282.092537532657], p586100: [-7781.41450138835, 0.0, 0.0, 0.0]}
kp: [4.0]
ki: [0.0]
kd: [0.35]
pwm_limit: [950.0]